import type { Metadata, Viewport } from "next";
import { JetBrains_Mono, Orbitron, Sarabun } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";

const orbitron = Orbitron({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-orbitron",
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-jetbrains",
  display: "swap",
});

const sarabun = Sarabun({
  subsets: ["latin", "thai"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-sarabun",
  display: "swap",
});

const SITE_DESCRIPTION = "เครื่องมือจูนโดรน FPV ครบครัน Tuning Wizard, Problem Solver, Calculator และ Preset Library";

// Resolves relative OG/Twitter image paths (e.g. "/og-image.svg") into
// absolute URLs. Set NEXT_PUBLIC_SITE_URL in your Render environment to
// your real domain (e.g. https://obixcore.onrender.com or a custom domain)
// so shared links show the right preview image instead of falling back to
// localhost.
const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: "OBIXCORE — FPV Tuning Platform",
  description: SITE_DESCRIPTION,
  keywords: ["FPV", "drone", "betaflight", "tuning", "PID", "preset", "โดรน"],
  openGraph: {
    title: "OBIXCORE — FPV Tuning Platform",
    description: SITE_DESCRIPTION,
    type: "website",
    images: [{ url: "/og-image.svg", width: 1200, height: 630, alt: "OBIXCORE FPV Tuning Platform" }],
  },
  twitter: {
    card: "summary_large_image",
    title: "OBIXCORE — FPV Tuning Platform",
    description: SITE_DESCRIPTION,
    images: ["/og-image.svg"],
  },
};

export const viewport: Viewport = {
  themeColor: "#050814",
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="th" className={`dark ${orbitron.variable} ${jetbrainsMono.variable} ${sarabun.variable}`}>
      <head>
        {/* viewport meta is now generated by the `viewport` export above —
            a hand-written one here would just duplicate/shadow it. */}
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
        <link rel="icon" type="image/png" href="/obixcore-icon.png" sizes="any" />
        <link rel="apple-touch-icon" href="/obixcore-icon.png" />
      </head>
      <body className="relative isolate min-h-screen overflow-x-hidden bg-bg font-sarabun text-text antialiased">
        <div className="pointer-events-none fixed inset-0 -z-30 bg-[radial-gradient(circle_at_top_left,_rgba(70,240,184,0.18),_transparent_28%),radial-gradient(circle_at_82%_16%,_rgba(99,179,255,0.14),_transparent_22%),radial-gradient(circle_at_16%_78%,_rgba(180,145,255,0.16),_transparent_24%),radial-gradient(circle_at_78%_82%,_rgba(255,209,102,0.10),_transparent_20%),linear-gradient(180deg,#050814_0%,#060912_44%,#050814_100%)]" />
        <div className="pointer-events-none fixed inset-0 -z-20 bg-grid opacity-35" />
        <div className="pointer-events-none fixed inset-0 -z-10 hud-noise" />
        <div className="pointer-events-none fixed inset-0 -z-10 scanline-overlay" />

        <div className="pointer-events-none fixed -top-28 -left-24 h-72 w-72 rounded-full bg-cyan-DEFAULT/15 blur-3xl animate-float-slow" />
        <div className="pointer-events-none fixed top-20 -right-24 h-80 w-80 rounded-full bg-blue-DEFAULT/14 blur-3xl animate-float-slower" />
        <div className="pointer-events-none fixed bottom-0 left-1/2 h-72 w-72 -translate-x-1/2 rounded-full bg-purple-DEFAULT/12 blur-3xl animate-float-slow" />

        <Nav />

        <main className="relative z-10 min-h-screen pb-24 md:pb-0 md:pt-24">
          {children}
        </main>
      </body>
    </html>
  );
}
